/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AcknowledgeEvent } from "./components/my-alert/my-alert";
import { TabActivateEvent } from "./components/my-tab/my-tab";
export { AcknowledgeEvent } from "./components/my-alert/my-alert";
export { TabActivateEvent } from "./components/my-tab/my-tab";
export namespace Components {
    interface CardExpirationInput {
        "error": boolean;
    }
    interface CardFormContainer {
    }
    interface CardHolderInput {
        "error": boolean;
    }
    interface CreditCardInput {
        "error": boolean;
    }
    interface CvvInput {
        "error": boolean;
    }
    interface ErrorMessage {
    }
    interface MyAlert {
        "kind": "info" | "success" | "error";
        "text": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyTab {
        "active": boolean;
        "name": string;
    }
    interface MyTabs {
        "activeTab": string;
    }
}
export interface CardExpirationInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCardExpirationInputElement;
}
export interface CardHolderInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCardHolderInputElement;
}
export interface CreditCardInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCreditCardInputElement;
}
export interface CvvInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCvvInputElement;
}
export interface MyAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyAlertElement;
}
export interface MyTabCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyTabElement;
}
declare global {
    interface HTMLCardExpirationInputElement extends Components.CardExpirationInput, HTMLStencilElement {
    }
    var HTMLCardExpirationInputElement: {
        prototype: HTMLCardExpirationInputElement;
        new (): HTMLCardExpirationInputElement;
    };
    interface HTMLCardFormContainerElement extends Components.CardFormContainer, HTMLStencilElement {
    }
    var HTMLCardFormContainerElement: {
        prototype: HTMLCardFormContainerElement;
        new (): HTMLCardFormContainerElement;
    };
    interface HTMLCardHolderInputElement extends Components.CardHolderInput, HTMLStencilElement {
    }
    var HTMLCardHolderInputElement: {
        prototype: HTMLCardHolderInputElement;
        new (): HTMLCardHolderInputElement;
    };
    interface HTMLCreditCardInputElement extends Components.CreditCardInput, HTMLStencilElement {
    }
    var HTMLCreditCardInputElement: {
        prototype: HTMLCreditCardInputElement;
        new (): HTMLCreditCardInputElement;
    };
    interface HTMLCvvInputElement extends Components.CvvInput, HTMLStencilElement {
    }
    var HTMLCvvInputElement: {
        prototype: HTMLCvvInputElement;
        new (): HTMLCvvInputElement;
    };
    interface HTMLErrorMessageElement extends Components.ErrorMessage, HTMLStencilElement {
    }
    var HTMLErrorMessageElement: {
        prototype: HTMLErrorMessageElement;
        new (): HTMLErrorMessageElement;
    };
    interface HTMLMyAlertElement extends Components.MyAlert, HTMLStencilElement {
    }
    var HTMLMyAlertElement: {
        prototype: HTMLMyAlertElement;
        new (): HTMLMyAlertElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyTabElement extends Components.MyTab, HTMLStencilElement {
    }
    var HTMLMyTabElement: {
        prototype: HTMLMyTabElement;
        new (): HTMLMyTabElement;
    };
    interface HTMLMyTabsElement extends Components.MyTabs, HTMLStencilElement {
    }
    var HTMLMyTabsElement: {
        prototype: HTMLMyTabsElement;
        new (): HTMLMyTabsElement;
    };
    interface HTMLElementTagNameMap {
        "card-expiration-input": HTMLCardExpirationInputElement;
        "card-form-container": HTMLCardFormContainerElement;
        "card-holder-input": HTMLCardHolderInputElement;
        "credit-card-input": HTMLCreditCardInputElement;
        "cvv-input": HTMLCvvInputElement;
        "error-message": HTMLErrorMessageElement;
        "my-alert": HTMLMyAlertElement;
        "my-component": HTMLMyComponentElement;
        "my-tab": HTMLMyTabElement;
        "my-tabs": HTMLMyTabsElement;
    }
}
declare namespace LocalJSX {
    interface CardExpirationInput {
        "error"?: boolean;
        "onChanged"?: (event: CardExpirationInputCustomEvent<string>) => void;
    }
    interface CardFormContainer {
    }
    interface CardHolderInput {
        "error"?: boolean;
        "onChanged"?: (event: CardHolderInputCustomEvent<string>) => void;
    }
    interface CreditCardInput {
        "error"?: boolean;
        "onChanged"?: (event: CreditCardInputCustomEvent<string>) => void;
    }
    interface CvvInput {
        "error"?: boolean;
        "onChanged"?: (event: CvvInputCustomEvent<string>) => void;
    }
    interface ErrorMessage {
    }
    interface MyAlert {
        "kind"?: "info" | "success" | "error";
        "onAcknowledge"?: (event: MyAlertCustomEvent<AcknowledgeEvent>) => void;
        "text"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyTab {
        "active"?: boolean;
        "name"?: string;
        "onTabActivate"?: (event: MyTabCustomEvent<TabActivateEvent>) => void;
    }
    interface MyTabs {
        "activeTab"?: string;
    }
    interface IntrinsicElements {
        "card-expiration-input": CardExpirationInput;
        "card-form-container": CardFormContainer;
        "card-holder-input": CardHolderInput;
        "credit-card-input": CreditCardInput;
        "cvv-input": CvvInput;
        "error-message": ErrorMessage;
        "my-alert": MyAlert;
        "my-component": MyComponent;
        "my-tab": MyTab;
        "my-tabs": MyTabs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "card-expiration-input": LocalJSX.CardExpirationInput & JSXBase.HTMLAttributes<HTMLCardExpirationInputElement>;
            "card-form-container": LocalJSX.CardFormContainer & JSXBase.HTMLAttributes<HTMLCardFormContainerElement>;
            "card-holder-input": LocalJSX.CardHolderInput & JSXBase.HTMLAttributes<HTMLCardHolderInputElement>;
            "credit-card-input": LocalJSX.CreditCardInput & JSXBase.HTMLAttributes<HTMLCreditCardInputElement>;
            "cvv-input": LocalJSX.CvvInput & JSXBase.HTMLAttributes<HTMLCvvInputElement>;
            "error-message": LocalJSX.ErrorMessage & JSXBase.HTMLAttributes<HTMLErrorMessageElement>;
            "my-alert": LocalJSX.MyAlert & JSXBase.HTMLAttributes<HTMLMyAlertElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-tab": LocalJSX.MyTab & JSXBase.HTMLAttributes<HTMLMyTabElement>;
            "my-tabs": LocalJSX.MyTabs & JSXBase.HTMLAttributes<HTMLMyTabsElement>;
        }
    }
}
